# Site Settings
title:               Lagrange
tagline:             a minimalist Jekyll theme
description:
baseurl:             ""
url:                 ""
github:
  url:               "https://github url"
author:
  name:              "name here"
  email:             "email here"
  github:            "github here"
  linkedin:          "linkedin here"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
