# Site Settings
title:               The blog's title
tagline:             A small description goes here
description:         One more description
baseurl:             ""
url:                 ""
github:
  url:               "https://jekyll-test.github.io"
author:
  name:              "name here"
  email:             "email here"
  github:            "github here"
  linkedin:          "linkedin here"
navigation:
- title: About
  url: /about

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
